CREATE TABLE "MLAPP"."COLUMNS_ROLES_MODEL_HIST" 
(
    "HIST_ID" NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "ROLE_ID" NUMBER NOT NULL,
    "DETAIL_ID" NUMBER NOT NULL,
    "MODEL_ID" VARCHAR2(64) NOT NULL,
    "DATAROLE" VARCHAR2(20 BYTE) NOT NULL,
    "DATE_FROM" TIMESTAMP (6),
    "DATE_TO" TIMESTAMP (6),
    "IS_ACTIVE" NUMBER(1,0) NOT NULL,
    "OPERATION_TYPE" VARCHAR2(10 BYTE) NOT NULL, -- INSERT, UPDATE, DELETE
    "CHANGED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL
)
;

CREATE OR REPLACE TRIGGER "MLAPP"."TRG_COLUMNS_ROLES_MODEL_HISTORY"
AFTER INSERT OR UPDATE OR DELETE ON "MLAPP"."COLUMNS_ROLES_MODEL"
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO "MLAPP"."COLUMNS_ROLES_MODEL_HIST"
        (
            "ROLE_ID", "DETAIL_ID", "MODEL_ID", "DATAROLE",
            "DATE_FROM", "DATE_TO", "IS_ACTIVE",
            "OPERATION_TYPE", "CHANGED_AT"
        )
        VALUES
        (
            :NEW.ROLE_ID, :NEW.DETAIL_ID, :NEW.MODEL_ID, :NEW.DATAROLE,
            :NEW.DATE_FROM, :NEW.DATE_TO, :NEW.IS_ACTIVE,
            'INSERT', CURRENT_TIMESTAMP
        );
    ELSIF UPDATING THEN
        INSERT INTO "MLAPP"."COLUMNS_ROLES_MODEL_HIST"
        (
            "ROLE_ID", "DETAIL_ID", "MODEL_ID", "DATAROLE",
            "DATE_FROM", "DATE_TO", "IS_ACTIVE",
            "OPERATION_TYPE", "CHANGED_AT"
        )
        VALUES
        (
            :NEW.ROLE_ID, :NEW.DETAIL_ID, :NEW.MODEL_ID, :NEW.DATAROLE,
            :NEW.DATE_FROM, :NEW.DATE_TO, :NEW.IS_ACTIVE,
            'UPDATE', CURRENT_TIMESTAMP
        );
    ELSIF DELETING THEN
        INSERT INTO "MLAPP"."COLUMNS_ROLES_MODEL_HIST"
        (
            "ROLE_ID", "DETAIL_ID", "MODEL_ID", "DATAROLE",
            "DATE_FROM", "DATE_TO", "IS_ACTIVE",
            "OPERATION_TYPE", "CHANGED_AT"
        )
        VALUES
        (
            :OLD.ROLE_ID, :OLD.DETAIL_ID, :OLD.MODEL_ID, :OLD.DATAROLE,
            :OLD.DATE_FROM, :OLD.DATE_TO, :OLD.IS_ACTIVE,
            'DELETE', CURRENT_TIMESTAMP
        );
    END IF;
END;
/
ALTER TRIGGER "MLAPP"."TRG_COLUMNS_ROLES_MODEL_HISTORY" ENABLE;

