CREATE TABLE MLAPP.MODELS (
    MODEL_ID varchar2(64) PRIMARY KEY ,
    MODEL_NAME VARCHAR2(100) NOT NULL UNIQUE,
    ESTIMATOR_CLASS VARCHAR2(255) NOT NULL,
    DATASET_NAME VARCHAR2(64) NOT NULL,  
    ESTIMATOR_PARAMETERS varchar2(1024),  -- JSON or serialized parameters
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    DELETED_AT TIMESTAMP, 
    CONSTRAINT FK_MODELS_DATASET_NAME FOREIGN KEY (DATASET_NAME)
        REFERENCES MLAPP.DATASETS (NAME)
);

CREATE OR REPLACE TRIGGER trg_generate_model_id
BEFORE INSERT ON MLAPP.MODELS
FOR EACH ROW
DECLARE
    v_hash VARCHAR2(64);
BEGIN
    IF :NEW.MODEL_ID IS NULL THEN
        EXECUTE IMMEDIATE
            'SELECT UPPER(SUBSTR(STANDARD_HASH(:1, ''SHA256''), 1, 64)) FROM DUAL'
            INTO v_hash
            USING :NEW.MODEL_NAME;
        :NEW.MODEL_ID := v_hash;
    END IF;
END;
/


CREATE OR REPLACE TRIGGER trg_update_model_timestamp
BEFORE UPDATE ON MLAPP.MODELS
FOR EACH ROW
BEGIN
    :NEW.UPDATED_AT := CURRENT_TIMESTAMP;
END;
/
