CREATE TABLE "MLAPP"."MODELS_HIST" 
(
    "HIST_ID" NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "MODEL_ID" VARCHAR2(64) NOT NULL,
    "MODEL_NAME" VARCHAR2(100 BYTE) NOT NULL,
    "ESTIMATOR_CLASS" VARCHAR2(255 BYTE) NOT NULL,
    "DATASET_NAME" VARCHAR2(64 BYTE) NOT NULL,
    "ESTIMATOR_PARAMETERS" VARCHAR2(1024 BYTE),
    "CREATED_AT" TIMESTAMP (6),
    "UPDATED_AT" TIMESTAMP (6),
    "DELETED_AT" TIMESTAMP (6),
    "OPERATION_TYPE" VARCHAR2(10 BYTE) NOT NULL, -- INSERT, UPDATE, DELETE
    "CHANGED_AT" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL
)
;

CREATE OR REPLACE TRIGGER "MLAPP"."TRG_MODELS_HISTORY"
AFTER INSERT OR UPDATE OR DELETE ON "MLAPP"."MODELS"
FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO "MLAPP"."MODELS_HIST" 
        (
            "MODEL_ID", "MODEL_NAME", "ESTIMATOR_CLASS", "DATASET_NAME",
            "ESTIMATOR_PARAMETERS", "CREATED_AT", "UPDATED_AT", "DELETED_AT",
            "OPERATION_TYPE"
        )
        VALUES
        (
            :NEW.MODEL_ID, :NEW.MODEL_NAME, :NEW.ESTIMATOR_CLASS, :NEW.DATASET_NAME,
            :NEW.ESTIMATOR_PARAMETERS, :NEW.CREATED_AT, :NEW.UPDATED_AT, :NEW.DELETED_AT,
            'INSERT'
        );
    ELSIF UPDATING THEN
        INSERT INTO "MLAPP"."MODELS_HIST" 
        (
            "MODEL_ID", "MODEL_NAME", "ESTIMATOR_CLASS", "DATASET_NAME",
            "ESTIMATOR_PARAMETERS", "CREATED_AT", "UPDATED_AT", "DELETED_AT",
            "OPERATION_TYPE"
        )
        VALUES
        (
            :NEW.MODEL_ID, :NEW.MODEL_NAME, :NEW.ESTIMATOR_CLASS, :NEW.DATASET_NAME,
            :NEW.ESTIMATOR_PARAMETERS, :NEW.CREATED_AT, :NEW.UPDATED_AT, :NEW.DELETED_AT,
            'UPDATE'
        );
    ELSIF DELETING THEN
        INSERT INTO "MLAPP"."MODELS_HIST" 
        (
            "MODEL_ID", "MODEL_NAME", "ESTIMATOR_CLASS", "DATASET_NAME",
            "ESTIMATOR_PARAMETERS", "CREATED_AT", "UPDATED_AT", "DELETED_AT",
            "OPERATION_TYPE"
        )
        VALUES
        (
            :OLD.MODEL_ID, :OLD.MODEL_NAME, :OLD.ESTIMATOR_CLASS, :OLD.DATASET_NAME,
            :OLD.ESTIMATOR_PARAMETERS, :OLD.CREATED_AT, :OLD.UPDATED_AT, :OLD.DELETED_AT,
            'DELETE'
        );
    END IF;
END;
/
ALTER TRIGGER "MLAPP"."TRG_MODELS_HISTORY" ENABLE;
