-- DROP TABLE MLAPP.BATCHSCORE_GENERATIONS;
CREATE TABLE MLAPP.BATCHSCORE_GENERATIONS (
    GENERATION_ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MODEL_NAME VARCHAR2(100) NOT NULL,
    GENERATION_DTTM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR2(20) NOT NULL,
    DETAILS VARCHAR2(256),
    CONSTRAINT FK_MODEL_NAME FOREIGN KEY (MODEL_NAME) REFERENCES MLAPP.MODELS(MODEL_NAME)
);
